[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
rand_core = { path = "../../../rand_core" }
rand = { path = "../../.." }
rand_distr = { path = "../../../rand_distr" }
rand_xoshiro = { path = "../../../rand_xoshiro" }
# Below does not require rand
rand_chacha = { path = "../../../rand_chacha" }
rand_hc = { path = "../../../rand_hc" }
rand_isaac = { path = "../../../rand_isaac" }
#rand_jitter = { path = "../../../rand_jitter" }
#rand_os = { path = "../../../rand_os" }
rand_xorshift = { path = "../../../rand_xorshift" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = {rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
